"""Regularization (Attendance Request) rules.

Regularizations are raised by the employee, not generated by the system, and each
employee may raise at most MONTHLY_LIMIT in a calendar month. HR/admin are exempt
so they can still fix things on someone's behalf.

When HR writes a warning/note on a regularization, the employee is told about it
in-app and by email. HR is also told as soon as one is raised - only HR/System
Manager can approve these (unlike Leave Application, a reporting manager has no
submit right here), so with no apply-notification these piled up unapproved for
weeks with nobody aware one was waiting.
"""

import frappe
from frappe.utils import getdate

MONTHLY_LIMIT = 3


def _has_full_access(user):
	from logikview_hr.permissions import FULL_ACCESS_ROLES
	return bool(FULL_ACCESS_ROLES & set(frappe.get_roles(user)))


def _hr_users():
	users = frappe.get_all("Has Role", filters={"role": ["in", ["HR Manager", "HR User"]],
	                                            "parenttype": "User"}, pluck="parent")
	return [u for u in set(users) if u and u != "Administrator"
	        and frappe.db.get_value("User", u, "enabled")]


def notify_hr_on_apply(doc, method=None):
	"""Tell HR as soon as a regularization is raised - they're the only ones who
	can approve it, and nothing else was telling them one was waiting."""
	hr = [u for u in _hr_users() if u != frappe.session.user]
	if not hr:
		return
	day = getdate(doc.from_date).strftime("%d %b %Y")
	if doc.to_date and doc.to_date != doc.from_date:
		day += " - " + getdate(doc.to_date).strftime("%d %b %Y")
	subject = f"Regularization awaiting approval - {doc.employee_name} ({day})"
	message = (f"{doc.employee_name} has raised a regularization for <b>{day}</b> "
	           f"({doc.get('reason') or 'no reason given'}). It needs HR approval "
	           f"before it's reflected in attendance.")
	from logikview_hr.notify import notify
	notify(hr, subject, message, doc.doctype, doc.name, dedup_key=f"applied-{doc.name}")


def check_monthly_limit(doc, method=None):
	"""At most MONTHLY_LIMIT regularizations per employee per calendar month."""
	if doc.flags.ignore_monthly_limit or _has_full_access(frappe.session.user):
		return
	if not doc.employee or not doc.from_date:
		return

	start = getdate(doc.from_date).replace(day=1)
	end = frappe.utils.get_last_day(start)
	used = frappe.db.count("Attendance Request", {
		"employee": doc.employee,
		"from_date": ["between", [start, end]],
		"docstatus": ["!=", 2],          # cancelled ones don't count
		"name": ["!=", doc.name or ""],
	})
	if used >= MONTHLY_LIMIT:
		frappe.throw(
			frappe._("You have already used all {0} regularization requests for {1}. "
			         "Please contact HR if you need another one.")
			.format(MONTHLY_LIMIT, start.strftime("%B %Y")),
			title=frappe._("Monthly limit reached"),
		)


@frappe.whitelist()
def monthly_usage(employee=None, on_date=None):
	"""How many of this month's regularizations the employee has used (for the form)."""
	if not employee:
		employee = frappe.db.get_value("Employee", {"user_id": frappe.session.user}, "name")
	if not employee:
		return {}
	start = getdate(on_date or frappe.utils.today()).replace(day=1)
	end = frappe.utils.get_last_day(start)
	used = frappe.db.count("Attendance Request", {
		"employee": employee,
		"from_date": ["between", [start, end]],
		"docstatus": ["!=", 2],
	})
	return {"used": used, "limit": MONTHLY_LIMIT, "left": max(0, MONTHLY_LIMIT - used),
	        "month": start.strftime("%B %Y")}


def mark_attendance_on_approval(doc, method=None):
	"""On approval, make sure every day the regularization covers actually reads as
	Present. Without this an approved request left the day Absent (or with no
	attendance row at all), so approving it changed nothing on the dashboard."""
	from frappe.utils import add_days, date_diff

	company = doc.get("company") or frappe.db.get_value("Employee", doc.employee, "company")
	day = getdate(doc.from_date)
	for _ in range(date_diff(doc.to_date, doc.from_date) + 1):
		existing = frappe.db.get_value("Attendance",
		                               {"employee": doc.employee, "attendance_date": day,
		                                "docstatus": ["!=", 2]}, ["name", "status"], as_dict=True)
		if existing:
			if existing.status != "Present":
				frappe.db.set_value("Attendance", existing.name, "status", "Present")
		else:
			att = frappe.get_doc({
				"doctype": "Attendance", "employee": doc.employee, "attendance_date": day,
				"status": "Present", "company": company,
			})
			att.flags.ignore_permissions = True
			att.flags.ignore_validate = True
			try:
				att.insert(ignore_permissions=True)
				frappe.db.set_value("Attendance", att.name, "docstatus", 1)
			except Exception:
				frappe.log_error(f"regularization attendance failed {doc.name} {day}",
				                 "Logikview Regularization")
		day = getdate(add_days(day, 1))
	frappe.db.commit()


def notify_warning(doc, method=None):
	"""Send the employee a notification when HR adds or changes the warning note."""
	note = (doc.get("custom_hr_warning") or "").strip()
	if not note:
		return

	before = doc.get_doc_before_save()
	if before and (before.get("custom_hr_warning") or "").strip() == note:
		return  # unchanged - don't nag on every save

	user = frappe.db.get_value("Employee", doc.employee, "user_id")
	if not user or user == frappe.session.user:
		return

	day = getdate(doc.from_date).strftime("%d %b %Y") if doc.from_date else ""
	category = doc.get("custom_late_category")
	subject = f"Note from HR on your regularization ({day})"
	message = (
		(f"<b>{category}</b><br>" if category else "")
		+ f"HR has added a note on your regularization for <b>{day}</b>:<br><br>"
		+ frappe.utils.escape_html(note).replace("\n", "<br>")
	)

	from logikview_hr.notify import notify
	notify([user], subject, message, doc.doctype, doc.name)
