"""Regularization (Attendance Request) rules.

Regularizations are raised by the employee, not generated by the system, and each
employee may raise at most MONTHLY_LIMIT in a calendar month. HR/admin are exempt
so they can still fix things on someone's behalf.

When HR writes a warning/note on a regularization, the employee is told about it
in-app (there is no SMTP on this bench).
"""

import frappe
from frappe.utils import getdate

MONTHLY_LIMIT = 3


def _has_full_access(user):
	from logikview_hr.permissions import FULL_ACCESS_ROLES
	return bool(FULL_ACCESS_ROLES & set(frappe.get_roles(user)))


def check_monthly_limit(doc, method=None):
	"""At most MONTHLY_LIMIT regularizations per employee per calendar month."""
	if doc.flags.ignore_monthly_limit or _has_full_access(frappe.session.user):
		return
	if not doc.employee or not doc.from_date:
		return

	start = getdate(doc.from_date).replace(day=1)
	end = frappe.utils.get_last_day(start)
	used = frappe.db.count("Attendance Request", {
		"employee": doc.employee,
		"from_date": ["between", [start, end]],
		"docstatus": ["!=", 2],          # cancelled ones don't count
		"name": ["!=", doc.name or ""],
	})
	if used >= MONTHLY_LIMIT:
		frappe.throw(
			frappe._("You have already used all {0} regularization requests for {1}. "
			         "Please contact HR if you need another one.")
			.format(MONTHLY_LIMIT, start.strftime("%B %Y")),
			title=frappe._("Monthly limit reached"),
		)


@frappe.whitelist()
def monthly_usage(employee=None, on_date=None):
	"""How many of this month's regularizations the employee has used (for the form)."""
	if not employee:
		employee = frappe.db.get_value("Employee", {"user_id": frappe.session.user}, "name")
	if not employee:
		return {}
	start = getdate(on_date or frappe.utils.today()).replace(day=1)
	end = frappe.utils.get_last_day(start)
	used = frappe.db.count("Attendance Request", {
		"employee": employee,
		"from_date": ["between", [start, end]],
		"docstatus": ["!=", 2],
	})
	return {"used": used, "limit": MONTHLY_LIMIT, "left": max(0, MONTHLY_LIMIT - used),
	        "month": start.strftime("%B %Y")}


def notify_warning(doc, method=None):
	"""Send the employee a notification when HR adds or changes the warning note."""
	note = (doc.get("custom_hr_warning") or "").strip()
	if not note:
		return

	before = doc.get_doc_before_save()
	if before and (before.get("custom_hr_warning") or "").strip() == note:
		return  # unchanged - don't nag on every save

	user = frappe.db.get_value("Employee", doc.employee, "user_id")
	if not user or user == frappe.session.user:
		return

	day = getdate(doc.from_date).strftime("%d %b %Y") if doc.from_date else ""
	category = doc.get("custom_late_category")
	subject = f"Note from HR on your regularization ({day})"
	message = (
		(f"<b>{category}</b><br>" if category else "")
		+ f"HR has added a note on your regularization for <b>{day}</b>:<br><br>"
		+ frappe.utils.escape_html(note).replace("\n", "<br>")
	)

	frappe.get_doc({
		"doctype": "Notification Log",
		"for_user": user,
		"type": "Alert",
		"document_type": doc.doctype,
		"document_name": doc.name,
		"subject": subject,
		"email_content": message,
	}).insert(ignore_permissions=True)
